import './App.css';
import Navbar from './components/Navbar';
import Hero from './components/Hero';


function App() {
  return (
    <div className="bg-[#050816] text-white">
      
      
      <Navbar/>
      <div id="section1"><Hero/></div>
      <div id="section2">Section 2 content goes here <br/><br/> Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/>Section 2 content goes here <br/><br/></div>
      {/* Add more sections as needed */}
      <div id="section3">Section 3 content goes here <br/><br/> Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/>Section 3 content goes here <br/><br/></div>
      <div id="section4">Section 4 content goes here <br/><br/> Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/>Section 4 content goes here <br/><br/></div>
      
      
    </div>
  );
}

export default App;
